# Copyright Red Hat

apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.admission.singapore.open-cluster-management.io
  annotations:
    "service.beta.openshift.io/inject-cabundle": "true"
spec:
  group: admission.singapore.open-cluster-management.io
  version: v1alpha1
  service:
    name: compute-operator-webhook-service
    namespace: {{ .Namespace }}
  groupPriorityMinimum: 10000
  versionPriority: 20
